package pojo;
// Generated 04-Feb-2021 13:36:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chatcreated generated by hbm2java
 */
public class Chatcreated  implements java.io.Serializable {


     private Integer chatid;
     private String chatname;
     private Date datecreated;
     private int status;

    public Chatcreated() {
    }

    public Chatcreated(String chatname, Date datecreated, int status) {
       this.chatname = chatname;
       this.datecreated = datecreated;
       this.status = status;
    }
   
    public Integer getChatid() {
        return this.chatid;
    }
    
    public void setChatid(Integer chatid) {
        this.chatid = chatid;
    }
    public String getChatname() {
        return this.chatname;
    }
    
    public void setChatname(String chatname) {
        this.chatname = chatname;
    }
    public Date getDatecreated() {
        return this.datecreated;
    }
    
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


