package pojo;
// Generated 04-Feb-2021 13:36:55 by Hibernate Tools 4.3.1



/**
 * Subscribers generated by hbm2java
 */
public class Subscribers  implements java.io.Serializable {


     private Integer id;
     private String chatid;
     private String userid;
     private int status;

    public Subscribers() {
    }

    public Subscribers(String chatid, String userid, int status) {
       this.chatid = chatid;
       this.userid = userid;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getChatid() {
        return this.chatid;
    }
    
    public void setChatid(String chatid) {
        this.chatid = chatid;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


