/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import controllerPackage.Controller;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.Transaction;
import pojo.User;

/**
 *
 * @author supun
 */
public class ChatSignup extends javax.swing.JFrame {

    /**
     * Creates new form ChatSignup
     */
    public ChatSignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unam = new javax.swing.JTextField();
        nicknam = new javax.swing.JTextField();
        useremail = new javax.swing.JTextField();
        conPwd = new javax.swing.JPasswordField();
        pwd = new javax.swing.JPasswordField();
        password1 = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        nick = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        signup_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(unam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 210, 40));
        getContentPane().add(nicknam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, 40));

        useremail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useremailActionPerformed(evt);
            }
        });
        getContentPane().add(useremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 210, 40));

        conPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conPwdActionPerformed(evt);
            }
        });
        getContentPane().add(conPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 210, 40));

        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 210, 40));

        password1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        password1.setText("Confirm Password");
        getContentPane().add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 140, 30));

        password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, 30));

        mail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        mail.setText("Email");
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 30));

        nick.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nick.setText("NickName");
        getContentPane().add(nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 30));

        username.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        username.setText("UserName");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 30));

        signup_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signup_btn.setText("Sign up");
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });
        getContentPane().add(signup_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 160, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Sign Up");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void useremailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useremailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useremailActionPerformed

    private void conPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conPwdActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed

        String username = unam.getText();
        String nickname = nicknam.getText();
        String email = useremail.getText();
        String password = pwd.getText();
        String confirmPwd = conPwd.getText();

        if (password.equals(confirmPwd)) {
            signup(username, nickname, email, password);
        } else {
            JOptionPane.showMessageDialog(null, "Password does not matched", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_signup_btnActionPerformed

    public void signup(String username, String nickname, String email, String password) {
        Session s = Controller.getSessionFactory().openSession();
        Transaction t = s.beginTransaction();
        User u = new User();
        //u.setImage(image);
        u.setUsername(username);
        u.setNickname(nickname);
        //u.setEmail(email);
        u.setPwd(password);
        u.setUsertype("client");

        s.save(u);
        t.commit();
     
        login signin = new login();
        signin.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField conPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel nick;
    private javax.swing.JTextField nicknam;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton signup_btn;
    private javax.swing.JTextField unam;
    private javax.swing.JTextField useremail;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
